messageformat: "&r[+prefix+group+suffix&r] +name: +message"

meformat: "&r* +rname +message"

timestampformat: hh:mm:ss

joinmessage: "&r&e+rname has joined the game"

leavemessage: "&r&e+rname has left the game"