name: nChat

main: com.niccholaspage.nChat.nChat

version: 0.9-SNAPSHOT

commands:
  nChat:
    usage: /<command>
    description: Allows you to view nChat's version and reload the configuration

depend: [Vault]